### ISSUE TITLE
Error on line 160 - using getLocale instead of getLanguage

### ISSUE THREAD

**Issue by albertinsyd** [salesforceidentity/IdentityTrail-Module3#2]
Module3RegistrationHandler  Lines 160-161 read as follows:

160        u.languagelocalekey = UserInfo.getLocale();
161        u.localesidkey = UserInfo.getLocale();

In fact, the first line should be using UserInfo.getLanguage() and not getLocale.

As currently written, this produces an error when a user registers - en_AU is not a valid Language value for the restricted picklist.  Changing the code to getLanguage resolves the problem.

**Comment by iglazer** [comment]
Thanks for the pull request. Merged in.
